# Generated by Django 5.2.6 on 2025-11-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_servicio_vehiculo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(
                to='Models.Cliente',
                on_delete=models.DO_NOTHING,
                db_column='usuario_id',
                null=True,
            ),
        ),
    ]
