# Generated by Django 5.2.6 on 2025-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='reserva',
            name='patente',
            field=models.CharField(blank=True, help_text='Ej: AB123CD', max_length=10, null=True),
        ),
    ]
